image: blacksalt/angulardart:latest

stages:
  - build

build:
  stage: build
  script:
    - pub global activate webdev
    - pub get
    - pub upgrade
    - webdev build
  artifacts:
    paths:
    - build/
