image: ubuntu:latest

stages:
  - build
  - deploy

build:
  stage: build
  image: google/dart:2
  only:
    - tags
    - triggers
    - schedules
    - web
  script:
    - pub global activate webdev
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - pub get
    - webdev build
  artifacts:
    paths:
    - build/

deploy:
  stage: deploy
  only:
    - tags
    - triggers
    - schedules
    - web
  script:
    - apt update
    - apt install -y make ssh
    - mv $MAKEMK make.mk
    - mkdir -p $HOME/.ssh && mv $RSA $HOME/.ssh/id_rsa && mv $KNOWN_HOSTS $HOME/.ssh/known_hosts
    - chmod 600 $HOME/.ssh/id_rsa
    - chmod 644 $HOME/.ssh/known_hosts
    - make deploy
