image: ubuntu:latest

stages:
  - build

build:
  stage: build
  script:
    - apt update
    - apt install apt-transport-https
    - sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
    - apt update
    - apt install dart
    - pub global activate webdev
    - pub get
    - pub upgrade
    - webdev build
  artifacts:
    paths:
    - build/
