image: ubuntu:latest

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - tags
    - triggers
    - schedules
    - web
  script:
    - apt update
    - apt install -y apt-transport-https curl gnupg git-core
    - sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
    - sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_unstable.list'
    - apt update
    - apt install -y dart
    - export PATH="$PATH:/usr/lib/dart/bin"
    - pub global activate webdev
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - pub get
    - webdev build
  artifacts:
    paths:
    - build/

deploy:
  stage: deploy
  only:
    - tags
    - triggers
    - schedules
    - web
  script:
    - apt update
    - apt install -y make
    - mv $MAKEMK make.mk
    - mkdir -p $HOME/.ssh && mv $RSA $HOME/.ssh/id_rsa
    - make deploy
