name: copyclient_ng
description: AStA Copyclient Web App using AngularDart
version: 0.3.11
homepage: https://asta.upb.de/
author: Leon Tappe <ltappe@asta.upb.de>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.2
  angular_forms: ^3.0.0
  blocs_copyclient:
    git: https://git.uni-paderborn.de/asta/blocs_copyclient.git
    #path: ../blocs_copyclient/
  logging: ^0.11.4
  angular_router: ^2.0.0
  mime: ^0.9.7
  intl: ^0.16.1

dev_dependencies:
  build_runner: ^1.10.4
  build_web_compilers: ^2.12.0
  sass_builder: ^2.1.3
  #intl_translation: ^0.17.10+1

