name: copyclient_ng
description: AStA Copyclient Web App using AngularDart
version: 0.3.2
homepage: https://asta.upb.de/
author: Leon Tappe <ltappe@asta.upb.de>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha
  angular_forms: ^2.1.2
  blocs_copyclient:
    git: https://git.uni-paderborn.de/asta/blocs_copyclient.git
  logging: 0.11.3+2
  angular_router: ^2.0.0-alpha+21

dev_dependencies:
  build_runner: ^1.5.2
  build_web_compilers: ^2.1.1
  sass_builder: ^2.1.3
