name: copyclient_ng
description: AStA Copyclient Web App using AngularDart
version: 0.1.0
homepage: https://asta.upb.de/
author: Leon Tappe <ltappe@asta.upb.de>

environment:
  sdk: '>=2.1.0-dev.7.1 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.0
  angular_forms: ^2.1.0
  http: ^0.12.0
  blocs_copyclient:
    git: https://git.uni-paderborn.de/asta/blocs_copyclient.git
  angular_bloc: ^0.2.1
  logger: ^0.3.1
  angular_router: ^2.0.0-alpha+20

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.0.0
  build_test: ^0.10.3+3
  build_web_compilers: ^0.4.4+2
  test: ^1.3.4