name: copyclient_ng
description: AStA Copyclient Web App using AngularDart
version: 0.3.0
homepage: https://asta.upb.de/
author: Leon Tappe <ltappe@asta.upb.de>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  angular_forms: ^2.1.2
  blocs_copyclient:
    git: https://git.uni-paderborn.de/asta/blocs_copyclient.git
  angular_bloc: ^0.9.0
  logging: 0.11.3+2
  angular_router: ^2.0.0-alpha+21

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^1.2.0
  sass_builder: ^2.1.2
