name: copyclient_ng
description: AStA Copyclient Web App using AngularDart
version: 0.3.9
homepage: https://asta.upb.de/
author: Leon Tappe <ltappe@asta.upb.de>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  angular_forms: ^2.1.2
  blocs_copyclient:
    version: ^1.0.1
    git: https://git.uni-paderborn.de/asta/blocs_copyclient.git
    #path: ../blocs_copyclient/
  logging: 0.11.3+2
  angular_router: ^2.0.0-alpha+21
  mime: ^0.9.6+3
  intl: ^0.15.8

dev_dependencies:
  build_runner: ^1.5.2
  build_web_compilers: ^2.1.1
  sass_builder: ^2.1.3
  intl_translation: ^0.17.4
